# Generated by Django 5.2.6 on 2025-09-06 04:38

from django.db import migrations
from pgvector.django import VectorExtension

class Migration(migrations.Migration):

    initial = True # Es la primera migración de esta app

    dependencies = [
    ]

    operations = [
        # Esta migración solo hace una cosa: activar la extensión
        VectorExtension(),
    ]